# mitm.py  — the man in the middle. Run this SECOND.
# You do NOT edit this file to switch encryption on or off. The attacker always
# tries to read and change every message. Encryption is what defeats it.
import socket

LISTEN_ADDRESS = ("127.0.0.1", 8000)     # the customer connects here, believing it is the bank
BANK_ADDRESS = ("127.0.0.1", 9000)       # the real bank


def is_readable(raw: bytes) -> bool:
    return all(32 <= b <= 126 for b in raw)   # true only if every byte is printable text


def redirect_receiver(text: str) -> str:
    # text looks like: "plain:TRANSFER 100 TO alice :: note"
    # Replace whoever comes after " TO " with the attacker's own account.
    head, marker, tail = text.partition(" TO ")
    if not marker:
        return text
    receiver, separator, note = tail.partition(" :: ")
    return f"{head} TO attacker{separator}{note}"


def handle(raw: bytes) -> bytes:
    if not is_readable(raw):
        print(f"[MITM] intercepted (scrambled): {raw.hex()}")
        print("[MITM] I cannot read this message. Tampering FAILED.")
        return raw

    text = raw.decode()
    print(f"[MITM] intercepted (readable): {text!r}")
    tampered = redirect_receiver(text)
    if tampered == text:
        print("[MITM] nothing to change. Tampering FAILED.")
        return raw
    print(f"[MITM] rewrote the receiver to 'attacker': {tampered!r}")
    print("[MITM] Tampering SUCCEEDED.")
    return tampered.encode()


with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as listener:
    listener.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    listener.bind(LISTEN_ADDRESS)
    listener.listen(1)
    print("[MITM] sitting in the middle, listening on port 8000")
    while True:
        customer, _ = listener.accept()
        with customer:
            print("\n" + "-" * 50)
            raw = customer.recv(1024)
            forwarded = handle(raw)
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as to_bank:
                to_bank.connect(BANK_ADDRESS)
                to_bank.sendall(forwarded)
                reply = to_bank.recv(1024)
            customer.sendall(reply)
